### ISSUE TITLE
 Unable to find Python libs

### ISSUE THREAD

**Issue by jasjuang** [rsgalloway/abcview#1]
I am on Ubuntu 16.04. I installed python by 

```
sudo apt-get install python python-dev
```

It is successfully installed because if I do a 

```
locate libpython
```

yields

```
/usr/lib/x86_64-linux-gnu/libpython2.7.a
/usr/lib/x86_64-linux-gnu/libpython2.7.so
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1
/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
...
```

However, if I do 

```
git clone https://github.com/alembic/abcview
cd abcview
mkdir build
cd build
cmake ..
```

yields 

```
-- make install dir: /usr/local
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   thread
--   chrono
--   system
--   date_time
--   atomic
-- BOOST INCLUDE DIRS: /usr/include
-- BOOST LIBRARIES: /usr/lib/x86_64-linux-gnu/libboost_program_options.a;/usr/lib/x86_64-linux-gnu/libboost_thread.a;/usr/lib/x86_64-linux-gnu/libboost_chrono.a;/usr/lib/x86_64-linux-gnu/libboost_system.a;/usr/lib/x86_64-linux-gnu/libboost_date_time.a;/usr/lib/x86_64-linux-gnu/libboost_atomic.a;/usr/lib/x86_64-linux-gnu/libpthread.so
-- ALEMBIC_LIB: /usr/local/lib/libAlembic.so
-- ALEMBIC_INCLUDE_PATH: /usr/local/include/Alembic
ILMBASE_ROOT is undefined
-- ILMBASE INCLUDE PATH: /usr/local/include/OpenEXR
-- HALF LIB: /usr/local/lib/libHalf.so
-- IEX LIB: /usr/local/lib/libIex-2_2.so
-- IEXMATH LIB: /usr/local/lib/libIexMath-2_2.so
-- ILMTHREAD LIB: /usr/local/lib/libIlmThread-2_2.so
-- IMATH LIB: /usr/local/lib/libImath-2_2.so
-- OpenGL Libraries: /usr/local/lib/libGLEW.so;/usr/lib/x86_64-linux-gnu/libglut.so;/usr/lib/x86_64-linux-gnu/libXmu.so;/usr/lib/x86_64-linux-gnu/libXi.so;/usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so
-- ABCOPENGL_DIR: /home/jasjuang/abcview/lib
-- LIBPYTHON_FILE: libpython2.6.a
-- PYTHON_ROOT: /usr/lib64/python2.6/config
-- PYTHON_LIBRARY: PYTHON_LIBRARY-NOTFOUND
-- Boost_PYTHON_LIBRARY: 
-- PYTHON_INCLUDE_DIR:/usr/include/python2.6
CMake Error at python/PyAbcOpenGL/CMakeLists.txt:116 (MESSAGE):
  Unable to find Python libs
```

Why is abcview unable to find python libraries when it is actually installed?

**Comment by rsgalloway** [comment]
I think it's actually complaining about not finding the boost python libs. The error message is misleading in that it only mentions Python libs, but the cmake file is looking for both:

https://github.com/alembic/abcview/blob/master/python/PyAbcOpenGL/CMakeLists.txt#L88

and from your cmake output it looks like it didn't find it:

`-- Boost_PYTHON_LIBRARY:`

Do you have boost python installed?

[edit: typo fix]

**Comment by jasjuang** [comment]
@rsgalloway I already installed boost python through

```
sudo apt-get install libboost-python-dev
```

If I do 

```
locate libboost_python
```

yields

```
/usr/lib/x86_64-linux-gnu/libboost_python-py27.a
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
/usr/lib/x86_64-linux-gnu/libboost_python-py35.a
/usr/lib/x86_64-linux-gnu/libboost_python-py35.so
/usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
/usr/lib/x86_64-linux-gnu/libboost_python.a
/usr/lib/x86_64-linux-gnu/libboost_python.so
```

Why can't it find Boost_PYTHON_LIBRARY?

EDIT: 

I looked into the CMakeLists.txt you pointed to. It seems like the variable `${Boost_PYTHON_LIBRARY}` is not being defined anywhere. I would expect at least something like `find_package(Boost REQUIRED)` in it.

**Comment by rsgalloway** [comment]
could it be because it's trying to find a python2.6 version?

`-- LIBPYTHON_FILE: libpython2.6.a`

try using -DLIBPYTHON_VERSION=2.7

**Comment by jasjuang** [comment]
@rsgalloway `cmake -DLIBPYTHON_VERSION=2.7 ..` 

yields the same error. Were you able to compile it successfully?

**Comment by rsgalloway** [comment]
Interestting. OK, I'll look into it further. In the meantime, try the 1.1.0 branch, you might have better luck.

```
git fetch
git checkout 1.1.0
```

Also, you can just build the WIP c++ version with -DUSE_PYTHON=OFF.

**Comment by jasjuang** [comment]
CMake successfully runs with -DUSE_PYTHON=OFF, but when compiling it shows an error  

```
fatal error: MainWindow.moc: No such file or directory
compilation terminated.
```

Also after `git checkout 1.1.0` CMake also successfully runs even without the need of -DUSE_PYTHON=OFF, but it leads to the same compilation error. Where is this MainWindow.moc file?

**Comment by rsgalloway** [comment]
Ok, great. Read the README. You need to have Qt installed and you'll need to generate the moc files, one for each header

`$ moc MainWindow.h -o MainWindow.moc`

Edit: at some point maybe I can get these to build via cmake, but for now you need to create them manually.

**Comment by jasjuang** [comment]
Thanks, I am able to build it successfully now
